In [11]:
import pandas as pd
path = r'C:\Users\amcho\Desktop\4th sem\ML lab\ML LAB5\master.csv'
try:
    df=pd.read_csv(path)
except Exception as e:
    print("Error reading the CSV file:", e)
df

,country,year,gender,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers
...,...,...,...,...,...,...,...,...,...,...,...,...
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers

In [12]:
df.country.value_counts()

country
Austria                   382
Mauritius                 382
Netherlands               382
Iceland                   382
Brazil                    372
                         ...
Bosnia and Herzegovina     24
Dominica                   12
Cabo Verde                 12
Macau                      12
Mongolia                   10
Name: count, Length: 101, dtype: int64

In [13]:
df.country.unique()

array(['Albania', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Barbados', 'Belarus', 'Belgium', 'Belize',
       'Bosnia and Herzegovina', 'Brazil', 'Bulgaria', 'Cabo Verde',
       'Canada', 'Chile', 'Colombia', 'Costa Rica', 'Croatia', 'Cuba',
       'Cyprus', 'Czech Republic', 'Denmark', 'Dominica', 'Ecuador',
       'El Salvador', 'Estonia', 'Fiji', 'Finland', 'France', 'Georgia',
       'Germany', 'Greece', 'Grenada', 'Guatemala', 'Guyana', 'Hungary',
       'Iceland', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Kazakhstan', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Latvia',
       'Lithuania', 'Luxembourg', 'Macau', 'Maldives', 'Malta',
       'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Norway', 'Oman', 'Panama', 'Paraguay',
       'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Republic of Korea', 'Romania', 'Russian Federation',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and Grenadines', 'San Marino', 'Serbia',
       'Seychelles', 'Singapore', 'Slovakia', 'Slovenia', 'South Africa',
       'Spain', 'Sri Lanka', 'Suriname', 'Sweden', 'Switzerland',
       'Thailand', 'Trinidad and Tobago', 'Turkey', 'Turkmenistan',
       'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United States', 'Uruguay', 'Uzbekistan'], dtype=object)

In [15]:
df[df['country']=='Sri Lanka']['suicides_no'].sum()

np.int64(55641)

In [23]:
cond1= df.country=='Sri Lanka'
cond2= df.year==1985
print(df[cond1 & cond2])
df[cond1 & cond2]['suicides_no'].sum()

         country  year  gender          age  suicides_no  population  \
23900  Sri Lanka  1985    male    75+ years          144      115000
23901  Sri Lanka  1985    male  15-24 years         1432     1673000
23902  Sri Lanka  1985    male  25-34 years         1024     1288000
23903  Sri Lanka  1985    male  55-74 years          443      680000
23904  Sri Lanka  1985  female  15-24 years          943     1652000
23905  Sri Lanka  1985    male  35-54 years          824     1469000
23906  Sri Lanka  1985  female  25-34 years          426     1268000
23907  Sri Lanka  1985  female    75+ years           23      106000
23908  Sri Lanka  1985  female  35-54 years          203     1402000
23909  Sri Lanka  1985  female  55-74 years           80      600000
23910  Sri Lanka  1985    male   5-14 years           71     1836000
23911  Sri Lanka  1985  female   5-14 years           55     1768000

       suicides/100k pop   country-year  HDI for year  gdp_for_year ($)   \
23900             125.22  Sri Lanka1985         0.597      5,978,460,972
23901              85.59  Sri Lanka1985         0.597      5,978,460,972
23902              79.50  Sri Lanka1985         0.597      5,978,460,972
23903              65.15  Sri Lanka1985         0.597      5,978,460,972
23904              57.08  Sri Lanka1985         0.597      5,978,460,972
23905              56.09  Sri Lanka1985         0.597      5,978,460,972
23906              33.60  Sri Lanka1985         0.597      5,978,460,972
23907              21.70  Sri Lanka1985         0.597      5,978,460,972
23908              14.48  Sri Lanka1985         0.597      5,978,460,972
23909              13.33  Sri Lanka1985         0.597      5,978,460,972
23910               3.87  Sri Lanka1985         0.597      5,978,460,972
23911               3.11  Sri Lanka1985         0.597      5,978,460,972

       gdp_per_capita ($)       generation
23900                 431  G.I. Generation
23901                 431     Generation X
23902                 431          Boomers
23903                 431  G.I. Generation
23904                 431     Generation X
23905                 431           Silent
23906                 431          Boomers
23907                 431  G.I. Generation
23908                 431           Silent
23909                 431  G.I. Generation
23910                 431     Generation X
23911                 431     Generation X

np.int64(5668)

In [25]:
cond1= df.country=='Sri Lanka'
cond2= df.year==2025
cond3= df.gender=='male'
print(df[cond1 & (cond2 | cond3)])

         country  year gender          age  suicides_no  population  \
23900  Sri Lanka  1985   male    75+ years          144      115000
23901  Sri Lanka  1985   male  15-24 years         1432     1673000
23902  Sri Lanka  1985   male  25-34 years         1024     1288000
23903  Sri Lanka  1985   male  55-74 years          443      680000
23905  Sri Lanka  1985   male  35-54 years          824     1469000
...          ...   ...    ...          ...          ...         ...
24021  Sri Lanka  2006   male  55-74 years          649     1187973
24022  Sri Lanka  2006   male  35-54 years         1246     2465505
24023  Sri Lanka  2006   male  25-34 years          573     1541529
24024  Sri Lanka  2006   male  15-24 years          423     1697398
24030  Sri Lanka  2006   male   5-14 years           15     1650300

       suicides/100k pop   country-year  HDI for year  gdp_for_year ($)   \
23900             125.22  Sri Lanka1985         0.597      5,978,460,972
23901              85.59  Sri Lanka1985         0.597      5,978,460,972
23902              79.50  Sri Lanka1985         0.597      5,978,460,972
23903              65.15  Sri Lanka1985         0.597      5,978,460,972
23905              56.09  Sri Lanka1985         0.597      5,978,460,972
...                  ...            ...           ...                ...
24021              54.63  Sri Lanka2006           NaN     28,267,410,543
24022              50.54  Sri Lanka2006           NaN     28,267,410,543
24023              37.17  Sri Lanka2006           NaN     28,267,410,543
24024              24.92  Sri Lanka2006           NaN     28,267,410,543
24030               0.91  Sri Lanka2006           NaN     28,267,410,543

       gdp_per_capita ($)       generation
23900                 431  G.I. Generation
23901                 431     Generation X
23902                 431          Boomers
23903                 431  G.I. Generation
23905                 431           Silent
...                   ...              ...
24021                1580           Silent
24022                1580          Boomers
24023                1580     Generation X
24024                1580       Millenials
24030                1580       Millenials

[66 rows x 12 columns]

In [30]:
df.loc[cond1 & (cond2 | cond3), ['country', 'year', 'gender', 'suicides_no']].head(10)

         country  year gender  suicides_no
23900  Sri Lanka  1985   male          144
23901  Sri Lanka  1985   male         1432
23902  Sri Lanka  1985   male         1024
23903  Sri Lanka  1985   male          443
23905  Sri Lanka  1985   male          824
23910  Sri Lanka  1985   male           71
23912  Sri Lanka  1986   male          145
23913  Sri Lanka  1986   male         1045
23914  Sri Lanka  1986   male         1304
23915  Sri Lanka  1986   male          461

In [ ]:
cond1= df.country=='Sri Lanka'
cond2= df.year==1985
cond3= df.gender=='male'
cond4= df.age=='15-24 years'
cd=df[cond1 & (cond2 | cond3) & cond4]
# cd['suicides_no'].sum()
print(cd.head(10))

         country  year  gender          age  suicides_no  population  \
23901  Sri Lanka  1985    male  15-24 years         1432     1673000
23904  Sri Lanka  1985  female  15-24 years          943     1652000
23914  Sri Lanka  1986    male  15-24 years         1304     1702300
23928  Sri Lanka  1996    male  15-24 years          768     1772399
23940  Sri Lanka  1997    male  15-24 years          924     1779781
23952  Sri Lanka  1998    male  15-24 years          740     1792565
23964  Sri Lanka  1999    male  15-24 years          765     1805721
23976  Sri Lanka  2000    male  15-24 years          615     1815183
23988  Sri Lanka  2001    male  15-24 years          508     1811743
24000  Sri Lanka  2002    male  15-24 years          520     1799884

       suicides/100k pop   country-year  HDI for year  gdp_for_year ($)   \
23901              85.59  Sri Lanka1985         0.597      5,978,460,972
23904              57.08  Sri Lanka1985         0.597      5,978,460,972
23914              76.60  Sri Lanka1986           NaN      6,405,210,564
23928              43.33  Sri Lanka1996           NaN     13,897,738,375
23940              51.92  Sri Lanka1997           NaN     15,091,913,884
23952              41.28  Sri Lanka1998           NaN     15,794,972,847
23964              42.37  Sri Lanka1999           NaN     15,656,327,860
23976              33.88  Sri Lanka2000         0.679     16,330,814,180
23988              28.04  Sri Lanka2001           NaN     15,749,753,805
24000              28.89  Sri Lanka2002           NaN     16,536,535,647

       gdp_per_capita ($)    generation
23901                 431  Generation X
23904                 431  Generation X
23914                 454  Generation X
23928                 834  Generation X
23940                 900  Generation X
23952                 935  Generation X
23964                 920  Generation X
23976                 953  Generation X
23988                 912    Millenials
24000                 951    Millenials